#   ___       ___  ___  ________   ________  ________  ___  ________  ________
#  |\  \     |\  \|\  \|\   ___  \|\   __  \|\   __  \|\  \|\   __  \|\   ___  \
#  \ \  \    \ \  \\\  \ \  \\ \  \ \  \|\  \ \  \|\  \ \  \ \  \|\  \ \  \\ \  \
#   \ \  \    \ \  \\\  \ \  \\ \  \ \   __  \ \   _  _\ \  \ \   __  \ \  \\ \  \
#    \ \  \____\ \  \\\  \ \  \\ \  \ \  \ \  \ \  \\  \\ \  \ \  \ \  \ \  \\ \  \
#     \ \_______\ \_______\ \__\\ \__\ \__\ \__\ \__\\ _\\ \__\ \__\ \__\ \__\\ \__\
#      \|_______|\|_______|\|__| \|__|\|__|\|__|\|__|\|__|\|__|\|__|\|__|\|__| \|__|

admin_prefix: "Victor Hugo > "

spawn:
  x: 0
  y: 0
  z: 0

banned_words: ["motinterdit1"]