#  ______   ___      ___ ___  ________ _________  ________  ________                 ___  ___  ___  ___  ________  ________  ______
# |\   ___\|\  \    /  /|\  \|\   ____\\___   ___\\   __  \|\   __  \               |\  \|\  \|\  \|\  \|\   ____\|\   __  \|\___   \
# \ \  \__|\ \  \  /  / | \  \ \  \___\|___ \  \_\ \  \|\  \ \  \|\  \  ____________\ \  \\\  \ \  \\\  \ \  \___|\ \  \|\  \|___|\  \
#  \ \  \   \ \  \/  / / \ \  \ \  \       \ \  \ \ \  \\\  \ \   _  _\|\____________\ \   __  \ \  \\\  \ \  \  __\ \  \\\  \   \ \  \
#   \ \  \___\ \    / /   \ \  \ \  \____   \ \  \ \ \  \\\  \ \  \\  \\|____________|\ \  \ \  \ \  \\\  \ \  \|\  \ \  \\\  \  _\_\  \
#    \ \______\ \__/ /     \ \__\ \_______\  \ \__\ \ \_______\ \__\\ _\               \ \__\ \__\ \_______\ \_______\ \_______\|\______\
#     \|______|\|__|/       \|__|\|_______|   \|__|  \|_______|\|__|\|__|               \|__|\|__|\|_______|\|_______|\|_______|\|______|                                                                                                         (_____)

name: VictorHugo
author: AegisLunarian
website: lunarian.fr
load: STARTUP
version: '1.0.1'
main: fr.aegislunarian.victorhugo.Main
api-version: '1.21'
commands:
  rank:
    aliases: [rang, gr]
    description: Commande relative à la gestion de rangs.
  msg:
    aliases: [pm, dm, message]
    description: Commande relative à l'envoi de messages.
  r:
    aliases: [repondre, respond, awnser, rep]
    description: Commande relative à la réponse aux messages.
  mod:
    aliases: [setmod, addmod, moderateur]
    description: Commande relative à la gestion des modérateurs.